version: 2.0

jobs:
  debian:
    docker:
      - image: debian:testing
    steps:
      - checkout
      - run:
          command: |
            apt update && apt -y install git gcc clang cmake libcriterion-dev 
            mkdir build && cd "$_"
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=ON ..
            make && make install
            ./tests/test_all

  ubuntu:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          command: |
            apt update && apt -y install git gcc clang cmake libcriterion-dev
            mkdir build && cd "$_"
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=ON ..
            make && make install
            ./tests/test_all

workflows:
  version: 2
  build:
    jobs:
      - debian
      - ubuntu
